services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: EduRequestSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: EduRequestSystemAPI/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TestDbString=Host=db;Port=5432;Database=EduRequestSystem;Username=postgres;Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
  
volumes:
  postgres_data_local:
